apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alertmanager
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    matchLabels:
      app: alertmanager
      monitored-by-prometheus: "true"
  namespaceSelector:
    any: true
  endpoints:
    - interval: 15s
      targetPort: web
      path: /metrics